[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA redirect - important for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self';"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optimize images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Preload critical resources
[[headers]]
  for = "/index.html"
  [headers.values]
    Link = "</assets/index.css>; rel=preload; as=style, </assets/index.js>; rel=preload; as=script"